- .travis.yml
Adding a linting step on Travis to catch style issues in the build
> build: add a linting step on travis

- .github/issue_template.md
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- package.json
This PR adds a CONTRIBUTING.md file with documentation on how to contribute to the project, a CODE_OF_CONDUCT, and templates for issues and PRs.
> Add CONTRIBUTING, CODE_OF_CONDUCT, and issue/pr templates

- package-lock.json
- package.json
`npm audit` was showing lots of vulnerabilities, yikes! This resolves every single one of them ✅ 
cc @christo4ferris
> build: update dependencies to remove vulnerabilities

- README.md
- auth/token-managers/iam-token-manager.ts
- auth/token-managers/jwt-token-manager.ts
- auth/utils/read-credentials-file.ts
- lib/base-service.ts
- lib/helper.ts
- lib/logger.ts
- lib/request-wrapper.ts
- package-lock.json
- package.json
- test/unit/iam-token-manager.test.js
- test/unit/logger.test.js
- test/unit/request-wrapper.test.js
Based on feedback I have added logging through the _debug_ module. Log messages are suppressed by default unless the specified environment variables in the README are set. I've gone ahead and updated some unit tests that broke after this change, added unit tests for the logger itself, and replaced all ``console.log`` references throughout the code.
> feat: adding debug logger

- auth/token-managers/jwt-token-manager.ts
- test/unit/jwt-token-manager.test.js
This PR adds a pacing method to regulate requests to the token service when the current token is invalid (never fetched) or expired. One caller is designated as the "active" request and it issues the request to the token server.  Subsequent requests create promises that are added to a list, and the active request resolves (or rejects) these as part of processing the token server response.
> feat: Pace requests to token server for new auth tokens

- auth/token-managers/token-manager.ts
- lib/base-service.ts
- lib/request-wrapper.ts
- test/unit/base-service.test.js
- test/unit/request-wrapper.test.js
Covered extra cases where trailing slash was not being removed when making a request.
> fix: Remove trailing slash from url for extra cases

- package.json
This is a fairly innocuous change whose main purpose
is to introduce a commit that will trigger a new release
of the library.
> fix: change description inside package.json

- .releaserc
- .travis.yml
- README.md
- scripts/jsdoc/publish.sh
This changeset updates the automation and documentation to support the new `main` default branch.
> fix(build): main migration

- package-lock.json
- package.json
This PR updates several dependencies of the project to avoid vulnerabilities.
> build: update deps to avoid vulnerabilities

- .secrets.baseline
- Authentication.md
Update authentication docs to mention `apikey` option in CP4D authenticator.
> docs: document apikey option in CP4D authenticator

- package-lock.json
- package.json
> fix(build): bump axios to 0.21.4 to avoid vulnerabilities

- .travis.yml
- package-lock.json
- package.json
This PR removes the codecov tool from the project due to security vulnerabilities.
> build: remove codecov from project

- .secrets.baseline
> chore: update secrets baseline to prevent false positive

- .secrets.baseline
- appscan-config.xml
> build: exclude testcases from ASoC scan

- MIGRATION-V4.md
> docs: fix typo in migration guide

- Authentication.md
Signed-off-by: Phil Adams <phil_adams@us.ibm.com>
> docs: add VPC-related note to auth docs

- .secrets.baseline
- package-lock.json
- package.json
This PR simply removes a few unused dependencies so that we can avoid unnecessary vulnerabilities.
Fixes: #245
> fix: remove unused dependencies

- etc/ibm-cloud-sdk-core.api.md
- lib/base-service.ts
- test/resources/mockSerDeService.js
- test/unit/serializer-deserializer.test.js
This PR introduces `createRequestAndDeserializeResponse` and `serializeModel` for serialization/deserialization feature.
> feat(serializer): add serializeModel and createRequestAndDeserializeResponse

- .travis.yml
- package-lock.json
- package.json
This PR bumps some of our dependencies to avoid vulnerabilities.
> build: bump dependencies to avoid vulnerabilities

- Authentication.md
Update the header to match the name used on line 5 of the file.
> docs: update header to match TOC list

- package-lock.json
References:
- https://github.com/micromatch/braces/pull/40
- https://github.com/micromatch/micromatch/issues/249
> fix(deps): bump `braces` and `micromatch` to avoid vulnerabilities

- lib/sdk-test-helpers.ts
- package-lock.json
- package.json
- test/unit/serializer-deserializer.test.js
This reverts commit b57b49108f17008fdf670ae2364edc908181773c.
Resolves #276
> fix: revert "fix(deps): remove `expect` as redundant development dependency"

- .secrets.baseline
- auth/authenticators/basic-authenticator.ts
- auth/authenticators/bearer-token-authenticator.ts
- auth/authenticators/token-request-based-authenticator.ts
- auth/token-managers/cp4d-token-manager.ts
- auth/token-managers/iam-request-based-token-manager.ts
- auth/token-managers/mcsp-token-manager.ts
- auth/token-managers/token-manager.ts
- auth/token-managers/vpc-instance-token-manager.ts
- auth/utils/read-external-sources.ts
- lib/base-service.ts
- lib/private-helpers.ts
- lib/request-wrapper.ts
- package-lock.json
- package.json
- sdk-test-utilities/package-lock.json
- sdk-test-utilities/package.json
- test/unit/container-token-manager.test.js
- test/unit/cp4d-token-manager.test.js
- test/unit/iam-request-based-token-manager.test.js
- test/unit/iam-token-manager.test.js
- test/unit/jwt-token-manager.test.js
- test/unit/mcsp-token-manager.test.js
- test/unit/redact-secrets.test.js
- test/unit/token-request-based-authenticator.test.js
- test/unit/vpc-instance-token-manager.test.js
This commit adds some debug logging in various components.
Edit: it also includes a more custom logger for http request/response messages
> fix(logging): improve node core's debug logging

- package-lock.json
- package.json
fix https://github.com/advisories/GHSA-fh7x-2848-jmpf
> fix(deps): update axios to resolve vulnerability

- package-lock.json
- package.json
> fix: update node types to align with required node versions
