IBM/node-sdk-core

lib/base_service.ts
test/unit/baseService.test.js

Allows ICP users to use the following pattern:
```js
const service = new SomeService({
iam_apikey: 'icp-1234abcd'
});
```
This will be converted internally to basic auth with a username of `apikey` and a password of `icp-1234abcd` (the typical pattern for authenticating ICP).
Test case included.

feat: allow ICP users to use `iam_apikey` to provide their key

---

lib/requestwrapper.ts
test/unit/requestWrapper.test.js

Make error handling consistent for next major release. First look in `errors[0].message`, then `error`, then `message`. Use the default status text if not found.
Tests included.

refeactor: make error handling consistent with other sdks

---

lib/base_service.ts
test/unit/baseService.test.js

To avoid a conflict with Watson Discovery (operation `getCredentials`), renaming `getCredentials` to `getServiceCredentials`

api change: rename getCredentials in BaseService to getServiceCredentials

---

package-lock.json
package.json

When I released v0.0.2, I did not build the JS code from TypeScript so the necessary changes were not released. I patched this by branching off of the v0.0.2 commit, making the changes, bumping the version to v0.0.3, publishing them, then reverting the package.json file back to the current version.
This PR just adds a `prepare` step to ensure this mistake won't be made again. This should be able to be removed once we add semantic release to the SDK.

Fix old version

---

lib/requestwrapper.ts

`axios` sets the default content type to `application/x-www-form-urlencoded`. This is problematic for operations like `createSession` in Assistant v2 , which is a POST but doesn't have a body or query parameters. The `axios` inserted header causes the service to choke. Sending `application/json` works fine and is consistent with how the other SDKs handle this problem.
This fix is required for the v4 release of the Watson Node SDK.

fix: make `application/json` the default content type

---

lib/requestwrapper.ts
test/unit/requestWrapper.test.js

Based on the error format of the IAM service, adding a field to check for when parsing the error - `errorMessage`. 
cc @joyychang

fix: parse error message from property errorMessage

---

lib/content-type.ts
test/unit/baseService.test.js

- Use `NodeJS.ReadableStream` instead of `ReadableStream` (which defaults to the type defined in the DOM library).
- This brings `ReadableStream`s usage in `content-type.ts` in line with all the other usage in this package (see https://github.com/IBM/node-sdk-core/issues/9#issuecomment-483523620).
Also:
- Gets linting to pass by fixing an `eslint` `no-unused-vars` error, and ignoring a `new-cap` error.

Use NodeJS.ReadableStream instead of DOM ReadableStream

---

.gitignore
iam-token-manager/v1.ts
test/unit/iamTokenManager.test.js

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/851
This PR includes these changes:
1. allow the clientid/secret values to be set by the user and then used during interactions with the IAM token server.   These values can be set in the following ways:
* via the Options object passed to the IamTokenManagerV1 ctor
* by calling the new IamTokenManager.setIamAuthorizationInfo() function
2. the default IAM token server URL was changed from "iam.bluemix.net" to "iam.cloud.ibm.com"

feat: allow IAM clientid/secret to be configured

---

iam-token-manager/v1.ts
lib/base_service.ts
package-lock.json
package.json

Upon further review of the `buffer-from` package, all it does is [provide a polyfill for the Node v4 style of creating buffers](https://github.com/LinusU/buffer-from/blob/master/index.js#L68).
Since we removed support for Node v4 in the last major release, this is no longer a necessary dependency. We can just use native buffers.

refactor: remove dependency on buffer-from and use native buffer

---

iam-token-manager/v1.ts
lib/base_service.ts
test/unit/baseService.test.js
test/unit/iamTokenManager.test.js

@padamstx added support for IAM Client ID and Secret credentials in the Token Manager, but I realized that users wouldn't be able to pass these credentials into service constructors without additions to the Base Service. This PR adds those changes w/ tests.

fix: allow iam client id and secret to be read from constructor

---

lib/base_service.ts
lib/requestwrapper.ts
package-lock.json
package.json
test/unit/requestWrapper.test.js

This allows users to set parameters on the `axios` config object using the service constructor.
Before this change, there is no way for the user to have any control over the `axios` configuration. In v3 of the SDK, we allowed parameters to be passed through to the `request` configuration, so this is consistent with that behavior. Maybe this is not something we want to do but I think it is helpful to the user.
Note that this only carries parameters from the service constructor, so it would apply to all requests. We could potentially make these parameters settable on a per-request basis but that would require more changes and is probably less desirable.

fix: carry user options from constructor to axios parameters

---

lib/read-credentials-file.ts
test/unit/readCredentialsFile.test.js

Related to: https://github.com/watson-developer-cloud/node-sdk/issues/865

fix: do not read credentials file in webpack override scenario

---

iam-token-manager/v1.ts
lib/base_service.ts
test/unit/baseService.test.js
test/unit/iamTokenManager.test.js

This PR renames `iam_secret` to `iam_client_secret` and `iamSecret` to `iamClientSecret` so that the node sdk core will be similar to other cores wrt IAM-related terminology.

fix(IAM): renamed UserOptions iam_secret to iam_client_secret to be consistent with other cores

---

lib/base_service.ts
lib/content-type.ts
test/unit/requestWrapper.test.js

This pull request refactors bluemix to cloud.ibm. `getCredentialsFromBluemix()` is a private method. Are we safe refactoring this to `getCredentialsFromIbmCloud`?

Refactor bluemix to cloud.ibm

---

lib/requestwrapper.ts
test/unit/requestWrapper.test.js

Currently, `204` responses (no content) get flagged as errors because `axios` chokes when it tries to unzip an empty response.
A fix for this bug has been merged ([see PR](https://github.com/axios/axios/pull/1129)) but has not been released yet. Since it looks like `axios` is not doing patch releases for bug fixes right now but is waiting for their next big release (0.19), we need to temporarily disable gzipping in the SDK.
We could do this only for operations that return a 204 but that would require generator changes so I think that would be more work than necessary, considering a fix for the bug seems to be in the somewhat near future.
If someone thinks that it would be worth it to do that, I'm happy to do it. Just let me know

fix: temporarily disable gzipping until axios bug fix is released

---

lib/requestwrapper.ts

This will prevent the circular JSON error when attempting to stringify the detailed response. The detailed response will include the status code, the status, the headers, and the data.

fix: remove node request objects from detailed response

---

lib/requestwrapper.ts
test/unit/requestWrapper.test.js

All of the other SDKs expose the body under the property `result`. We currently are using the `axios` convention of `data`.
This PR adds `result` to the response holding the same information as `data`, leaving `data` in for compatibility (to be removed at a later time).
Tests included. A PR will be opened against the generator to match this on the SDK side.
cc @mkistler @germanattanasio

fix: expose the body in the detailed response under the field `result`

---

lib/base_service.ts
package-lock.json
package.json
test/unit/baseService.test.js

When the IAM Client ID and Secret parameters were added, I forgot to include them in the `getServiceCredentials` and `getCredentialsFromEnvironment` methods. They should be included here so they can be specified as environment variables like any other credential parameter.

fix: read iam client id and secret from environment variables

---

.travis.yml
migration-guide.md
package.json

BREAKING CHANGE: This SDK may no longer work with applications running on Node 6 or 8.
First official commit to the v1 release candidate branch.

build: drop support for Node versions 6 and 8

---

lib/requestwrapper.ts
migration-guide.md
test/unit/requestWrapper.test.js

Returns the "detailed response" (which includes the body, the headers, the status, etc.) as the first callback argument after error. This used to be the body itself, so this is a breaking change (pushing to the "next" branch).
Also, renaming the body property from `data` to `result`. This is done to be consistent with the other SDKs.
This will remove the need for the generated SDKs to use the `return_response` parameter to determine how to resolve Promises.
Includes some test changes.

Return detailed response

---

lib/base_service.ts

We expose the `axios` config options in the constructor but we don't allow any flexibility in the constructor options type. This will allow TypeScript users to use the request parameters like the `axios` config properties.

fix: extend constructor options type to allow additional properties

---

auth/iam-token-manager-v1.ts
auth/icp4d-token-manager-v1.ts
auth/jwt-token-manager-v1.ts
lib/base_service.ts
test/unit/base-service-integration.test.js

This will allow users to configure all requests, rather than just the service requests. This was causing a bug where users could not use the SDK behind a corporate proxy. They could specify the proxy for the service request but the IAM request would error.

fix: share service request wrapper instance with token managers

---

auth/authenticators/index.ts
auth/authenticators/no-auth-authenticator.ts
auth/utils/get-authenticator-from-environment.ts
test/unit/base-service.test.js
test/unit/get-authenticator-from-environment.test.js
test/unit/no-auth-authenticator.test.js

Update all instances of the word "noauth" to be two words - "no auth" - using language specific naming conventions.

refactor: rename noauth authenticator to noAuth authenticator

---

auth/utils/get-authenticator-from-environment.ts
lib/base_service.ts
lib/requestwrapper.ts
migration-guide.md
test/unit/base-service.test.js
test/unit/get-authenticator-from-environment.test.js
test/unit/requestWrapper.test.js

Also...
* Change `url` to `serviceUrl`
* Validate that `serviceUrl` is set in the `sendRequest` method
* Make "auth type" case-insensitive
* Throw an error for unsupported "auth types" - only default to 'iam' when no "auth type" is provided
BREAKING CHANGE: The internal property `url` no longer exists on the `baseOptions` object, it has been renamed to `serviceUrl`
Tests and migration guide updated.

feat: add `setServiceUrl` method as a setter for the `serviceUrl` property

---

lib/base_service.ts
lib/helper.ts
lib/requestwrapper.ts
test/unit/requestWrapper.test.js

This PR fixes the handling of array form parameters.
In a `multipart/form-data` request body, an array property should be serialized as multiple form data parts, each with the name of the array property and one of the elements of the array.
I've also added documentation for the primary exported method, `createRequest`, and refactored the processing of file properties to make it simpler/clearer.

Fix handling of array form parameters

---

lib/base_service.ts
lib/requestwrapper.ts
test/unit/base-service.test.js
test/unit/requestWrapper.test.js

This PR moves the check for a non-empty serviceUrl to the createRequest method, so that sendRequest can be used from the authenticators which just pass `url`.
In addition, createRequest will take serviceUrl from the service baseOptions if none was provided in  parameters.defaultOptions.
Tests were updated accordingly.

fix: Move check for serviceUrl to createRequest

---

lib/helper.ts
test/unit/buildRequestFileObject.test.js

The PR fixes the backward incompatibility for FileObjects passed as files in formData.
I removed support for FileObjects in a previous PR because I thought it was not needed or used, but  subsequently discovered that some users do use it.  So I've reimplemented support for FileObjects and restored all the tests I had deleted in the previous PR.

Fix backward compatibility for FileObjects 

---

auth/authenticators/authenticator.ts
auth/authenticators/basic-authenticator.ts
auth/authenticators/bearer-token-authenticator.ts
auth/authenticators/cloud-pak-for-data-authenticator.ts
auth/authenticators/iam-authenticator.ts
auth/authenticators/token-request-based-authenticator.ts
auth/token-managers/cp4d-token-manager.ts
auth/token-managers/iam-token-manager.ts
auth/token-managers/jwt-token-manager.ts
auth/utils/get-authenticator-from-environment.ts
auth/utils/helpers.ts
lib/base_service.ts

* refactor validate method to be used across authenticators/token mangers
* add types for token manager properties in authenticators
* add return type for `getAuthenticatorFromEnvironment`
* return `Error` object in `checkCredentials` rather than a `string`
* add setters for `disableSslVerification` and `headers` in token managers so we can use stricter typing
* Make `authenticator` optional in the base service options
This last point needed to be done to compile the Watson SDKs - TypeScript does not allow you to declare an optional parameter on an interface that extends another interface where the same parameter is required. We aren't _exactly_ extending the interface (although I think we should) but we use the "extended" interface in a place where the base interface is expected and TS …

minor refactoring for the authentication changes

---

index.ts
lib/base_service.ts

Export this type to be used in the generated subclasses.

feat: export `UserOptions` interface from the BaseService

---

package-lock.json
package.json

Upgrades the version of typescript used from 2.9 to ^3.4 which matches the dependency versioning for https://github.com/watson-developer-cloud/node-sdk. I had to also upgrade the version of `tslint-estlint-rules` and `@types/node` to accommodate the version upgrade.
This is a blocker for #52 as the `unknown` type was added in TypeScript 3.

build(deps): upgrade typescript from 2 to 3

---

lib/requestwrapper.ts
test/unit/requestWrapper.test.js

Adds a specific handler for ICP SSL errors. Also fixes the dreaded "Body is HTTP blah blah" error with a more descriptive one.

Handle ssl errors

---

package-lock.json
package.json
tsconfig.json

This changes the installed `@types` file to use the right typing package for the isstream module that is depended upon concretely.

chore: replace @types/is-stream with correct @types/isstream

---

auth/authenticators/authenticator-interface.ts
auth/authenticators/authenticator.ts
auth/authenticators/basic-authenticator.ts
auth/authenticators/bearer-token-authenticator.ts
auth/authenticators/no-auth-authenticator.ts
auth/authenticators/token-request-based-authenticator.ts
auth/token-managers/cp4d-token-manager.ts
auth/token-managers/iam-token-manager.ts
auth/token-managers/jwt-token-manager.ts
lib/base_service.ts
lib/requestwrapper.ts
test/unit/base-service.test.js
test/unit/basic-authenticator.test.js
test/unit/bearer-token-authenticator.test.js
test/unit/cp4d-authenticator.test.js
test/unit/cp4d-token-manager.test.js
test/unit/iam-authenticator.test.js
test/unit/iam-token-manager.test.js
test/unit/jwt-token-manager.test.js
test/unit/no-auth-authenticator.test.js
test/unit/request-token-based-authenticator.test.js
test/unit/requestWrapper.test.js

Refactors the entire library to use Promises instead of callbacks. This is a pretty big change but since the SDK is really the only "user", I don't think it will cause any problems.
The generated SDK code should be able to change slightly to achieve no difference in current behavior. The current plan is to start returning Promises first in the generated Watson SDK, with callbacks being an accommodation. We also want to start generating new services using only Promises. This PR enables that route, as it moves all callback handling out of the core and into the generated SDK.
If this is too big of a change to make too late in the game, that's fine, but this work is necessary to move towards a Promise-only approach and doing it this way gives us more flexibility in the generated SDKs to use …

feat: refactor core to use Promises instead of callbacks

---

auth/utils/read-credentials-file.browser.ts
package.json

This change uses the `browser` [property](https://docs.npmjs.com/files/package.json#browser) to allow browser users leveraging bundlers like webpack (in Angular and React projects) to use the Node SDK Core and its consumers out of the box. Previously, React users needed to configure polyfills for webpack in order to trick the dependency resolution for **dotenv** and **fs**.
These changes will require removing instructions in the **ibm-watson** Node SDK documentation about how to consume these packages in client environments.

fix: provide bundlers alternate file for browser support

---

lib/base_service.ts
test/unit/baseService.test.js

From my understand and talking with @dpopp07, with the release of the v5 API SDK, the `ibm-credentials.env` file is going to change format from:
```
TEXT_TO_SPEECH_IAM_APIKEY=my_api_key
TEXT_TO_SPEECH_URL=https://stream.watsonplatform.net/text-to-speech/api
```
to be:
```
TEXT_TO_SPEECH_APIKEY=my_api_key
TEXT_TO_SPEECH_URL=https://stream.watsonplatform.net/text-to-speech/api
```
This PR allows the v4 API to consume this new format to make things slightly less painful for those of us who cannot immediately upgrade to v5, but would like to continue downloading these env files when setting up new services in the meantime.

feat: allow node-sdk-core 0.x to work with new ibm-crendentials.env

---

lib/base-service.ts
test/unit/base-service.test.js

Fixes: https://github.ibm.com/arf/planning-sdk-squad/issues/1118
Changes:
- moved the external configuration code outside of the constructor into it's own method.
- for compatibility, the constructor calls the new method until we move to the service factory's complete implementation.
The new method will now be invoked from the generator after the BaseService's constructor is called.

feat: adding configureService method for external config options

---

.npmignore

Updates the `.npmignore` file as some number of non-package files were being included in the npm archive on installation.
Note, per documentation on [package.json#Keeping Files Out of Your Package](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package), there are a number of files that are always implicitly ignored and recommended to not include them in the `.npmignore` file, which for this repo include:
* LICENSE
* CHANGELOG.md
* node_modules
* .DS_Store
I was not sure if the following files were supposed to be ignored or not as well so I did not add them to the file:
* AUTHENTICATION.md
* MIGRATION-V1.md

build: update npmignore to include some missed files

---

auth/authenticators/authenticator-interface.ts
auth/authenticators/authenticator.ts
auth/authenticators/basic-authenticator.ts
auth/authenticators/bearer-token-authenticator.ts
auth/authenticators/cloud-pak-for-data-authenticator.ts
auth/authenticators/iam-authenticator.ts
auth/authenticators/index.ts
auth/authenticators/no-auth-authenticator.ts
auth/authenticators/token-request-based-authenticator.ts
auth/token-managers/cp4d-token-manager.ts
auth/token-managers/iam-token-manager.ts
auth/token-managers/index.ts
auth/token-managers/jwt-token-manager.ts
auth/utils/get-authenticator-from-environment.ts
auth/utils/helpers.ts
auth/utils/index.ts
auth/utils/read-credentials-file.ts
auth/utils/read-external-sources.ts
lib/base-service.ts
lib/content-type.ts
lib/helper.ts
lib/querystring.ts
lib/stream-to-promise.ts
package-lock.json
scripts/typedoc/generate_typedoc.sh
test/unit/basic-authenticator.test.js
test/unit/cp4d-authenticator.test.js

Enhance documentation for the node-sdk-core
FAQ
**Removing the implements AuthenticatorInterface` everywhere`**?:
In the typedoc it would show that the Authenticators implemented the interface twice. Which felt confusing to me. They already implement it through the Authenticator.
**The refactor of the authentication logic in the BasicAuthenticator**?
Same changes were made during commenting of the python core. Can be reversed if needed.

Documentation for node-sdk-core

---

tsconfig.json

Similar to https://github.com/watson-developer-cloud/node-sdk/pull/989
This disables the generation of source maps from `tsc`. The source maps are only really useful if the original `.ts` files are there, which for consumers of the npm package, they are not, so these files just take up space for no benefit.

build: disable generation of source maps

---

package-lock.json
package.json
test/utils/index.ts
test/utils/unit-test-helpers.ts

This fixes Issue #993 in the 'watson-developer-cloud/node-sdk' repository (https://github.com/watson-developer-cloud/node-sdk/issues/993)

fix(release): convert test utils to .ts

---

lib/base-service.ts
test/unit/base-service.test.js

This fixes a bug in which generated SDK code would not actually use the default URL if none was provided.

fix: use constant defined by generated sdks for url

---

lib/request-wrapper.ts

The fields `status` and `statusText` are now added to the response error, to be consistent with the fields on a successful response object. The other fields are left intact for compatibility but are marked as deprecated so we know to remove them in the next major release.

fix: use consistent fields between success and error response objects

---

CONTRIBUTING.md
auth/token-managers/jwt-token-manager.ts
test/unit/iam-token-manager.test.js
test/unit/jwt-token-manager.test.js

This PR modifies the token refresh logic to pace refresh requests to avoid exceeding rate-limiting by the token server.  This design also improves performance by continuing to use an existing token while the refresh is performed concurrently.
I also cleaned up some misinformation in the `CONTRIBUTING.md` that I uncovered in the process of developing this change.

Pace token refresh requests to avoid rate-limiting

---

README.md
lib/base-service.ts
lib/request-wrapper.ts
package-lock.json
package.json
test/unit/base-service.test.js
test/unit/cookiejar.test.js

This adds cookie jar support to Axios using [axios-cookiejar-support](https://github.com/3846masa/axios-cookiejar-support), so that consumers of the core can provide their own cookie jar management capabilities depending on the needs of their users.
This PR simply adds tests to #84 - I opened a separate PR to avoid commit history conflicts since I rebased onto `master` and just amended Christian's commit

feat: add optional cookie jar support

---

auth/token-managers/jwt-token-manager.ts
test/unit/jwt-token-manager.test.js

This changes the exposure level of the `saveTokenInfo` method to be "protected" instead of "private" so that developers implementing a subclass can override that method as needed.
Additionally, this changes `saveTokenInfo` to accept the entire response and extract the body within the method. That way, there can be subclass implementations for authentication mechanisms that include the token somewhere other than the body, like the headers.
Reviewers: let me know if you think this is a breaking change. I decided that it was not because the only "contract" change is happening for `saveTokenInfo` (the argument changed) but that method was previously marked as "private". The `getToken` method was changed but the public contract is not affected by the change. I may be missing something though.

expose the `saveTokenInfo` to subclasses

---

lib/request-wrapper.ts
test/unit/request-wrapper.test.js

Trailing slashes weren't being removed in the sendRequest method after the service URL and path url were combined. This resolves that problem.

feat: Strip trailing slashes in sendRequest

---

lib/helper.ts
test/unit/get-missing-params.test.js

Currently, we are checking for "truthyness" when evaluating if required parameters have been set or not. This is flawed - when required params are set to `false`, they are incorrectly being flagged as missing.
This PR fixes that bug by explicitly checking for the `undefined` value. Test case added to support the fix.

fix: flag required params as missing when explicitly undefined

---

auth/token-managers/cp4d-token-manager.ts
auth/token-managers/iam-token-manager.ts
auth/token-managers/index.ts
auth/token-managers/jwt-token-manager.ts
auth/token-managers/token-manager.ts
auth/utils/helpers.ts
test/unit/iam-token-manager.test.js
test/unit/jwt-token-manager.test.js

The new `TokenManager` class will be responsible only for the token handling specifically.
Changed some private fields to protected: `tokenInfo`, `expireTime`, `refreshTime`.
Placed `getCurrentTime` into the utils module to be globally usable.

Introduce a token-manager class for token handling

---

test/resources/ibm-credentials.env
test/unit/read-credentials-file.test.js
test/unit/read-external-sources.test.js

This PR simply adds unit tests to confirm/test  that the core tolerates an "=" within a config property value.
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/1759

chore: add unit tests for tolerating an = in config property

---

package.json

Updates axios to ^0.18.1 in the package.json as 0.18.0 had a [CVE](https://app.snyk.io/vuln/SNYK-JS-AXIOS-174505) where it would not destroy a stream before throwing an error about it exceeding the max size, which could cause a potential DoS.
There was no other change in 0.18.1 other than fixing this bug.
Related to #93, and while a new version of this (and bumping the version cloud foundry) uses would probably fix it, sounds like rebuilds are using a package-lock.json that pins to an older version of axios.

chore: bump axios to ^0.18.1

---

package-lock.json
package.json

Updates jest and ts-jest to ^25.5. This fixes npm reporting a vulnerability when installing this module as a dependency. This will also fix potential incompatibilities of ts-jest in this repository and https://github.com/watson-developer-cloud/node-sdk which uses jest^25.

chore: bump jest, ts-jest to ^25.5

---

auth/authenticators/basic-authenticator.ts
auth/authenticators/bearer-token-authenticator.ts
auth/authenticators/token-request-based-authenticator.ts
auth/token-managers/cp4d-token-manager.ts
auth/token-managers/iam-token-manager.ts
auth/token-managers/jwt-token-manager.ts
auth/utils/get-authenticator-from-environment.ts
lib/base-service.ts
lib/helper.ts
lib/request-wrapper.ts
package-lock.json
package.json

This commit replaces all instances of 'extend' with Object.assign and removes 'extend' as a package dependency.

chore: Remove 'extend' dependency

---

lib/request-wrapper.ts
test/unit/request-wrapper.test.js

Before, if a user set `disableSslVerification` to true and also provided their own httpsAgent (to configure a proxy, etc), the `disableSslVerification` handling would be overwritten. We would create an httpsAgent with the required property, but the user's agent would get used instead.
Now, if the user provides their own agent, the code will update the user's agent to add the required property. This way, if a user ever specifies `disableSslVerification` to true, it will always be handled properly at the agent level.

fix: support `disableSslVerification` when user provides custom httpsAgent

---

package-lock.json
package.json

v3.9 of `typescript` includes changes that break our code. The top-level exports in `index.js` are generated without "setters", so individual components of this core module cannot be mocked in tests.
This does not impact normal operation of the code (that I'm aware of - there's reason to redefine any components when using them) but it causes issues in the generated unit tests for SDKs that rely on this package. These tests mock out individual components to isolate behavior. By pinning the dependency to 3.8.3, we can continue to mock these components.
FYI @apaparazzi0329

fix: pin typescript dependency to 3.8.3

---

auth/authenticators/iam-authenticator.ts
auth/token-managers/iam-token-manager.ts
test/resources/ibm-credentials.env
test/unit/get-authenticator-from-environment.test.js
test/unit/iam-authenticator.test.js
test/unit/iam-token-manager.test.js
test/unit/read-credentials-file.test.js
test/unit/read-external-sources.test.js

The IAM /identity/token (get token) operation supports an optional "scope" form parameter which can be used to obtain an IAM access token having a limited set of scopes in this it can be used.
This commit adds support for the "Scope" field within the IamTokenManager & IamAuthenticator class. If set, the value of this field is sent as the "scope" form param in the "get token" request body when obtaining an access token.
ref: https://github.ibm.com/arf/planning-sdk-squad/issues/2167

feat(IAM Authenticator): add support for optional 'scope' property

---

lib/request-wrapper.ts
package-lock.json
package.json
test/unit/request-wrapper.test.js

I spent some time today reading through the `axios` docs and issue and I _think_ it should be fine to upgrade to the latest version (0.20.0). It seems to be much more actively maintained than it has been the past year or so, which makes me more comfortable about upgrading. There seem to have been [a couple of unintentional breaking changes](https://github.com/axios/axios/issues/3294#issuecomment-696601393) in this version but neither of them affect us because of how we're using the library in our code.
In addition to this version bump, I added the `gzip` encoding on responses back in, which was waiting on a fix within `axios`.

feat: upgrade axios and re-enable gzipping responses

---

auth/utils/read-external-sources.ts
lib/base-service.ts
lib/request-wrapper.ts
test/unit/base-service.test.js
test/unit/read-external-sources.test.js
test/unit/request-wrapper.test.js

A flag can now be passed to the BaseService that will enable gzip compression on the request body data. This flag is passed down to the RequestWrapper class where the compression code lives. Note that no code needs to be changed in the BaseService - the options passed into its constructor will be carried through to the RequestWrapper. In the generated code, I am planning on attaching the flag to the options passed into the BaseService constructor.
If there is a problem during compression, the code moves alone with the request, just uncompressed. If this is not the behavior we want, I can change it.

feat: add support for compressing request bodies

---

appscan-config.xml

The changes in the `appscan-config` file will exclude the `/scripts` directory in our security scanning tool.

chore: appscan configuration file

---

.releaserc
package-lock.json
package.json

This version of `semantic-release` includes breaking changes that I have addressed in the
`.releaserc` file. The only change that affects us is that "branch" was renamed to "branches"
to accept multiple values. It can still accept a single string value so I only renamed the property value.
Opening this to replace #113

build: update semantic-release to v17

---

auth/authenticators/iam-authenticator.ts
auth/token-managers/iam-token-manager.ts
test/unit/iam-token-manager.test.js

The `IamAuthenticator` class now makes the refresh token available to users through
a public method, `getRefreshToken`. This provides support to services that require
the refresh token as a part of their authentication scheme.
Note that this is only supported for the IAM authenticator. Let me know if we need the same support in the CP4D authenticator.

feat(iam-authenticator): expose refresh token with a getter

---

lib/base-service.ts
test/unit/base-service.test.js

When a new `BaseService` instance is created, the class settings are stored in an object
called `baseOptions`. Currently, when the `setEnableGzipCompression` method is called,
the `enableGzipCompression` setting is not changed and might no longer reflect the state
of the setting (because it is primarily tracked in the underlying `RequestWrapper` class).
This PR addresses this by persisting the setting in the `baseOptions` object when that method
is called so that the object always reflects the accurate value for the setting.

fix: persist `enableGzipCompression` setting on the base service

---

.gitignore
.secrets.baseline
auth/authenticators/cloud-pak-for-data-authenticator.ts
auth/token-managers/cp4d-token-manager.ts
test/integration/cp4d-authenticator.test.js
test/resources/cp4dtest.env.example
test/unit/cp4d-authenticator.test.js
test/unit/cp4d-token-manager.test.js

This commit enhances the CP4D Authenticator to support the username/apikey use case.
With these changes, a user has the ability to construct a CP4D authenticator using
either a username/password pair or a username/apikey pair. The authenticator will
now use the official "POST /v1/authorize" operation for obtaining an access token.
I followed [the Go changes](https://github.com/IBM/go-sdk-core/pull/88/files) pretty closely but let me know if I missed something.
Phil, I hope you don't mind that I copied your commit message 🙂

feat: support username/apikey use-case in CloudPakForDataAuthenticator

---

lib/helper.ts
test/unit/get-query-param.test.js

This PR adds a small utility method to extract the value of a query parameter from a URL string. This will be used in the pagination support for Node.

Add getQueryParam utility method to support pagination

---

auth/utils/read-credentials-file.ts
test/resources/symlink-creds.txt
test/unit/read-credentials-file.test.js

Currently, credentials files are explicitly required to real files (not symbolic links).
This was to exclude directories, not to exclude symbolic links, so it is a bug.
This PR adds explicit support for symbolic links. This should be a robust solution, as
I do not believe we want to support any of the other types the file could be (sockets,
block devices, etc).

fix: enable symbolic-link credentials files

---

lib/sdk-test-helpers.browser.ts
package.json

The "sdk-test-helpers" file contains helper functions that generated SDKs use
in their generated unit tests. These functions are never actually needed when
running standard operational code, therefore they are never used in the browser.
The `expect` library that we use for testing has a dependency that isn't browser
friendly in certain scenarios. This causes the core and any SDKs importing it
to throw errors in these scenarios (like the React framework).
This change stubs the sdk-test-helpers in browser environments the same way we
stub the credentials file reading code. I've verified that this fix works in the problematic environments
cc @apaparazzi0329

fix: stub sdk-test-helpers in browser environments

---

package-lock.json
package.json

This PR upgrades the jest and typedoc dependencies to avoid pulling in vulnerable versions of downstream dependencies.

build: upgrade dependencies to avoid vuln alerts

---

package-lock.json

This PR updates package-lock.json back to v2 (npm v7.x).  Otherwise, there shouldn't be any actual changes to dependency versions.   An `npm audit` run in my local sandbox yielded 0 vulnerabilities (knock on wood!).

fix: upgrade package-lock.json

---

lib/base-service.ts
test/unit/parameterized-url.test.js

This method can be used by an API to construct a service URL from a parameterized URL.

feat: add `BaseService.constructServiceURL` method

---

test/unit/request-wrapper.test.js

This PR adds a couple of request-wrapper unit tests to verify that when the Host header is explicitly set in the Axios options, it appears to be included in the http request mesage.

test: add tests that explicitly set the Host request header

---

lib/base-service.ts
lib/helper.ts
test/unit/parameterized-url.test.js

Now it can be used as a utility function instead of an inherited method.
An SDK class can now include a `constructServiceURL` method with a different signature than this function.

fix: change constructServiceURL from method to function

---

.travis.yml

Node 10 is deprecated, so we want to test on the latest stable versions of Node, 12 and 14.

build: remove deprecated Node 10 version from CI build

---

lib/request-wrapper.ts
test/unit/request-wrapper.test.js

The `axios` library sets an arbitrary maximum length for request bodies and
throws an error if this length is exceeded. This has caused some confusion for
users and none of the other core libraries enforce such a limit. Services are
expected to handle request body length themselves. So this commit overrides the
default to be "Infinity", just like we do for response body limits. Users still
have the option to override this limit if they wish.

fix: remove default limit on request body length

---

lib/querystring.ts
scripts/jsdoc/template/tmpl/layout.tmpl
test/unit/querystring.test.js

We currently have a special hack to handle watson tokens in a unique way.
This used to be required for Watson services but they have not used this
method of authentication in years. This is supposed to be a service-agnostic
package, so this commit refactors the code to avoid the specific handling.
I also edited a jsdoc file (even though I don't think it is used) and added
a test for this small module.

refactor: remove specific handling for "watson-token" query params

---

.secrets.baseline
auth/token-managers/iam-request-based-token-manager.ts
auth/token-managers/iam-token-manager.ts
auth/token-managers/index.ts
auth/utils/helpers.ts
package-lock.json
test/unit/iam-request-based-token-manager.test.js
test/unit/iam-token-manager.test.js
test/unit/logger.test.js

This will allow other token managers that interact with the IAM service to share configuration and functionality. This change is being made in advance of a new container-based token manager being added that will utilize this shared functionality, as it will interact with the IAM service as well.
cc @pyrooka

refactor: move iam-specific functionality to a shared class 

---

.secrets.baseline
Authentication.md
README.md
auth/authenticators/container-authenticator.ts
auth/authenticators/iam-authenticator.ts
auth/authenticators/iam-request-based-authenticator.ts
auth/authenticators/index.ts
auth/token-managers/container-token-manager.ts
auth/token-managers/index.ts
auth/utils/file-reading-helpers.browser.ts
auth/utils/file-reading-helpers.ts
auth/utils/get-authenticator-from-environment.ts
auth/utils/helpers.ts
auth/utils/index.ts
auth/utils/read-external-sources.ts
test/resources/vault-token
test/unit/container-authenticator.test.js
test/unit/container-token-manager.test.js
test/unit/file-reading-helpers.test.js
test/unit/get-authenticator-from-environment.test.js
test/unit/iam-authenticator.test.js
test/unit/iam-request-based-authenticator.test.js

This PR adds an authenticator and token manager for the new "container" flavor of authentication. This style retrieves a compute resource token from the file system and uses that to retrieve an IAM access token, which is used to authenticate with the service.
Note: I realized that I refactored the IAM token manager but not the authenticator. It really should be both, so as part of this PR I refactored the authenticator to match the refactoring in the token manager.

feat: add support for new ContainerAuthenticator

---

package-lock.json
package.json

Typescript v3.9 contains breaking changes relative to v3.8. These changes
affect generated SDK projects that use a core package built with TS 3.9.
Specifically, the generated unit tests in the SDK project are prevented
from running. In the future, we may want to upgrade to Typescript v4 - this
will likely require updates to our generated code to be compatible. Until
then, we need to stick with 3.8.x.

fix: use typescript 3.8.x to build the published code

---

auth/utils/get-authenticator-from-environment.ts
test/resources/ibm-credentials.env
test/unit/get-authenticator-from-environment.test.js
test/unit/read-external-sources.test.js

fix: support 'AUTHTYPE' as alias for 'AUTH_TYPE' config property

---

.secrets.baseline
lib/base-service.ts
lib/request-wrapper.ts
test/unit/base-service.test.js
test/unit/request-wrapper.test.js

This new method is added to the base service class so that all initialized SDK client objects
have access to the underlying axios instance used to make requests. This instance is currently
hidden as a private class member. This functionality is already supported in the other language
cores, so this brings feature parity

feat: add method `getHttpClient` to get underlying axios instance of base service

---

package-lock.json
package.json

This PR makes a simple change to package.json to add the "all" script (e.g. `npm run all`) which will build, unit test and lint-check the project.

build: add 'npm run all' command to simplify project builds

---

lib/request-wrapper.ts
test/unit/request-wrapper.test.js

I stumbled across https://github.com/axios/axios/issues/2829 when investigating a performance issue in our SDK that extends the core. The performance issue described in that issue can be avoided by using `-1` instead of `Infinity` to set a preference for having no `maxContentLength`.
Since the purpose of `Infinity` here is to have no limit, using `-1` should make no difference to the expected behaviour, but it does avoid the performance problem (at least until such time as axios have a fix for it). In the profiling of my particular scenario having `maxContentLength` enabled was causing 25% of all ticks to be spent in `Buffer` `concat` which was having a dramatic performance impact.

perf: use maxContentLength -1 instead of Infinity

---

package-lock.json
package.json
test/unit/base-service.test.js
test/unit/basic-authenticator.test.js
test/unit/bearer-token-authenticator.test.js
test/unit/cp4d-authenticator.test.js
test/unit/jwt-token-manager.test.js
test/unit/no-auth-authenticator.test.js
test/unit/request-wrapper.test.js

I updated to the latest version of `Jest`, which removes the dependency on `set-value`.

build: update vulnerable dependencies

---

.cra/.cveignore

This PR configures the CRA scan to avoid  the ansi-regex vulnerability alert.

build: avoid ansi-regex vuln alerts

---

.secrets.baseline
Authentication.md
auth/authenticators/authenticator.ts
auth/authenticators/container-authenticator.ts
auth/authenticators/index.ts
auth/authenticators/vpc-instance-authenticator.ts
auth/token-managers/index.ts
auth/token-managers/vpc-instance-token-manager.ts
auth/utils/get-authenticator-from-environment.ts
auth/utils/helpers.ts
test/unit/get-authenticator-from-environment.test.js
test/unit/vpc-instance-authenticator.test.js
test/unit/vpc-instance-token-manager.test.js

This commit introduces the VpcInstanceAuthenticator.
This authenticator implements the authentication flow
within a VPC-managed compute resource that is configured to
use the compute resource identity feature.
This involves the use of the compute resource's local
VPC Instance Metadata Service API to retrieve an instance identity
token, and then exchange that token for an IAM access token.
The IAM access token is then used to authenticate outbound REST
API requests by adding an Authorization containing the access token.

feat(VpcInstanceAuthenticator): add support for new VPC authentication flow

---

auth/token-managers/vpc-instance-token-manager.ts
test/unit/vpc-instance-token-manager.test.js

This PR fixes a small problem in the VPC instance token manager related to the "default profile" scenario.
Previously, the token manager would send an empty request body (i.e. `{ }`) if both `iamProfileId` and `iamProfileCrn` were both unspecified.  This would cause a 400 Bad Request to be returned by the VPC Instance Metadata Service.
The fix is to simply avoid sending a request body at all for this scenario.

fix(VpcInstanceAuthenticator): omit request body for default profile scenario

---

.cra/.cveignore
package-lock.json
package.json

This PR contains a few changes to our dependency versions to avoid vulnerability alerts.
I also removed the contents of the .cveignore file since that is no longer needed.

fix: bump dependencies to avoid vulnerability alerts

---

lib/request-wrapper.ts
lib/stream-to-promise.ts
test/unit/to-promise.test.js

`streamToPromise` calls `toString()` on the `concat`ed `Buffer` which [defaults to `utf-8` encoding](https://nodejs.org/api/buffer.html#buftostringencoding-start-end) and consequently can mangle non `utf-8` content. This problem surfaced via https://github.com/IBM/cloudant-node-sdk/issues/546.
* Remove `toString()` call when using `Buffer` type.
The problem is resolved by _not_ calling `toString()` as the `Buffer` bytes may be passed as-is to the server for a byte stream. In cases where the stream is using `string` or `objectMode` _not_ `Buffer` then the existing `Buffer.isBuffer(results[0])` check puts the chunk as-is into the `results` array (i.e. it is an array of strings or objects).
* Update doc in streamToPromise to indicate it is not always text.
* Add test for binary type stream. …

fix: don't always convert bytes to text in streamToPromise

---

lib/request-wrapper.ts
test/unit/request-wrapper.test.js

This is similar to the problem fixed by #182 but in this case for `Buffer` request body data instead of a `ReadableStream`.
The fix in this case is if the `data` is already a `Buffer` then just compress it, don't convert it to a `string` and back to a `Buffer` again before compressing it.
I added a test with `Buffer` input. I chose the input carefully to ensure that if it was assumed to be `UTF-8` encoded it would not be the same when decompressed and added an additional assertion for the decompressed data to match the original.

fix: avoid Buffer re-encode during compression

---

package.json

A recent change to the library introduced
a separate es6 module for the library to support
tree shaking.  Unfortunately, if an SDK project
doesn't (at a minimum) define the 'main' entry point
in its package.json file, then a problem can occur
due to an es5 vs es6 incompatibility.
This commit provides a tactical fix for this issue
by removing the 'module' entry point from the library's
package.json.  This will prevent webpack from being
able to minimize the resulting application code, but
it will avoid the problem.
Once we have a strategy for rolling out "tree
shakability" in various SDK projects, we can
re-introduce the 'module' entry point.

fix: remove 'module' entry from package.json

---

lib/request-wrapper.ts

Fixes https://github.com/IBM/node-sdk-core/issues/179
This commit slightly modifies how requests and responses
are logged when debug logging is enabled to avoid
any JSON marshalling type errors.
We no longer use JSON.stringify() to format
the request and response objects, as they
actually aren't needed because the
logger.debug() and logger.error() functions
can handle objects just fine and do a decent job
of pretty-printing them.

fix: avoid errors during logging of requests/responses

---

package-lock.json

This PR includes an update to package-lock.json that bumps up the version of follow-redirects in order to avoid a snyk vulnerability.

fix: bump version of follow-redirects to avoid vulnerability

---

lib/request-wrapper.ts
test/unit/retry.test.js

The other SDK cores skip retry for `501`,
so the Node core should behave the same way.

fix: do not retry on 501

---

package.json

A recent change seems to have removed the creation of the `dist/docs/`
folder during the build and as such, the `cp` command we invoke was
renaming the JSON docs file as a new file with the name `docs`.
This change ensures a folder called `dist/docs/` is created if one
is not already present.
Resolves #201

fix: ensure dist/docs is a directory during build

---

etc/ibm-cloud-sdk-core.api.md
lib/helper.ts
lib/request-wrapper.ts
package-lock.json
package.json
test/unit/build-request-file-object.test.js
test/unit/get-content-type.test.js

Resolves #204 
The CVE states that v16.5.4 is clean, so I upgraded to that and modified the code accordingly. It led to some function changes from sync to async but all functions that should really only be used internally. That said, I think these functions are technically exported as part of the public API, so we should evaluate if this should considered a breaking change or a necessary fix of broken (vulnerable) code.
I wanted to upgrade to v17 but that caused a number of TypeScript errors from the `file-type` internal code. I may open an issue there to see if I can find out why it's happening.

fix: update file-type to resolve vulnerability

---

auth/authenticators/authenticator-interface.ts
auth/authenticators/authenticator.ts
auth/authenticators/basic-authenticator.ts
auth/authenticators/token-request-based-authenticator.ts
etc/ibm-cloud-sdk-core.api.md

The interface incorrectly defined the data channel as "void or Error" when it
should only be "void", as Errors are sent in a different channel. This updates
the type to be correct. It should not constitute a breaking update as we
already defined authenticators with the new type in this project.
Resolves #176

fix: correct AuthenticatorInterface type

---

etc/ibm-cloud-sdk-core.api.md
lib/base-service.ts
test/unit/base-service.test.js

This change adds a setter for the default headers stored on the base service.
These headers are sent with every SDK request. All of the other language cores
supported setting these values post-construction so this brings Node to parity.

feat: add `setDefaultHeaders` method on base service class

---

etc/ibm-cloud-sdk-core.api.md
index.ts
lib/get-new-logger.ts
lib/logger.ts
test/unit/get-new-logger.test.js
test/unit/logger.test.js

This method will return a new logger configured with a provided name. This can be used by generated service classes to create a new logger specific to its module context.

feat: add method `getNewLogger` to public API

---

lib/request-wrapper.ts

This issue was caused by an oversight in adding an `await` statement within a `forEach` loop, which will result in asynchronous operations happening without the synchronous control you'd expect from async/await.
This solves the issue by simply converting the loops to "for of" loops.
This caused a subtle server error so unfortunately, I can't think of a great test case for it. I should've known not to put an `await` call within a `forEach` though. Logically, this is a simple refactor, but practically it makes the code behave in the way it was actually intended to.
cc @apaparazzi0329

fix: allow for synchronous building of file requests

---

test/integration/iam-authenticator.test.js

This PR adds an integration test for the IAM Authenticator so that
we can easily run a test against the production or staging IAM server.

test: add IAM integration test

---

package-lock.json
package.json

The current version of `nock` uses `lodash.set` which is vulnerable. They've resolved this in the latest version.

build: update `nock` to resolve security vulnerability

---

lib/cookie-support.ts
lib/request-wrapper.ts
package-lock.json
package.json
test/unit/cookiejar.test.js

Attempts to upgrade to axios 1.x (#209/#213) have been impeded by incompatibilities with `axios-cookiejar-support`:
* 1.x version is [incompatible with newer axios versions](https://github.com/3846masa/axios-cookiejar-support/issues/310)
* 2.x+ versions are [incompatible with retries](https://github.com/3846masa/axios-cookiejar-support/issues/602)
Remove axios-cookiejar-support depdenency.
This PR:
* Removes `axios-cookiejar-support` dependency.
* Adds `cookie-support.ts` for providing axios interceptors to interact with `tough-cookie`.
* Updates the cookiejar tests for the above.

refactor: cookie support via interceptors

---

auth/token-managers/jwt-token-manager.ts
package-lock.json
package.json
test/unit/iam-token-manager.test.js
test/unit/jwt-token-manager.test.js

There is a vulnerability in v8 of the `jsonwebtoken` dependency. This commit upgrades to v9 to resolve the vulnerability. Additionally, they made an effort in this version to discourage the less secure "decode" method in favor of the more secure "verify" method. This commit also refactors the code and tests to use the "verify" method.

fix(auth): migrate to secure usage of jwt for token authentication

---

auth/token-managers/jwt-token-manager.ts
test/unit/iam-token-manager.test.js
test/unit/jwt-token-manager.test.js

The move to `verify` was a bit shortsighted. It requires a public key or secret as an argument to verify the signed token. Typical usage of IBM's IAM service doesn't lend itself to this flow and the tokens returned don't have valid JWT signatures. This led to a runtime error everytime the core made an IAM request - a bit of a showstopping bug.
Additionally, we never had a goal of performing client-side validation of these tokens, we only decode them to determine the expiration time for usage in our refresh logic. The `decode` method is perfectly sufficient for that and indeed is called within the `verify` method anyways. Perhaps this flow will change in the future but this is all we need for now.
This reverts the logic to what we were using before but still using the safe version of the …

fix(auth): revert to using decode instead verify for jwt

---

package-lock.json

This PR bumps the json5 dependency to avoid a vulnerability.

build: bump json5 to avoid vulnerability

---

auth/token-managers/vpc-instance-token-manager.ts
test/unit/vpc-instance-token-manager.test.js

This PR modifies the VpcInstanceAuthenticator to use the correct value for the version query parameter ("2022-03-01").

fix(VpcInstanceAuthenticator): use correct version string

---

etc/ibm-cloud-sdk-core.api.md
lib/helper.ts
lib/request-wrapper.ts
test/unit/is-json-mime-type.test.js
test/unit/request-wrapper.test.js

Error response bodies are currently returned as strings, even when the content is JSON. This is a bug - the SDK should return the result as an object. This commit adds logic to return the result as an object, converting it if necessary.
It also updates the error object to use the "result" field for the response body, in order to be consistent with the success path. The "body" field is still set for backward-compatibility but is marked as deprecated.
Additionally, for both success and error responses, if the content is JSON but the result cannot be parsed as an object, an exception will be raised, alerting the user that the service returned a malformed body.
cc @ricellis

fix: return json error response body as object

---

lib/request-wrapper.ts
test/unit/request-wrapper.test.js

There are cases, such as a HEAD request, where the response body will have a JSON content type but the body will be empty (i.e. an empty string). This is technically valid JSON but is not parsable into an object, so the code throws an exception. This commit adds specific handling for this scenario, as well as a couple of test cases

fix: correctly handle empty response bodies

---

lib/cookie-support.ts
package-lock.json
package.json

The aim of this PR is to bump `axios` from `1.2.1` to `1.4.0`. There was a type change in https://github.com/axios/axios/pull/5486 that was applied in [`1.2.4`](https://github.com/axios/axios/releases/tag/v1.2.4), so the request interceptor gets `InternalAxiosRequestConfig` config instead of the previous `AxiosRequestConfig`.

build(deps): bump axios from 1.2.1 to 1.4.0

---

Authentication.md
auth/token-managers/container-token-manager.ts
auth/utils/file-reading-helpers.ts
etc/ibm-cloud-sdk-core.api.md
test/unit/container-authenticator.test.js
test/unit/container-token-manager.test.js
test/unit/file-reading-helpers.test.js

This PR modifies the ContainerAuthenticator so that it supports a second default CR token
filename.

fix(ContainerAuthenticator): add sa-token as default CR token filename

---

auth/authenticators/basic-authenticator.ts
auth/authenticators/bearer-token-authenticator.ts
auth/authenticators/cloud-pak-for-data-authenticator.ts
auth/authenticators/container-authenticator.ts
auth/authenticators/iam-authenticator.ts
auth/authenticators/iam-request-based-authenticator.ts
auth/authenticators/index.ts
auth/authenticators/token-request-based-authenticator.ts
auth/authenticators/vpc-instance-authenticator.ts
auth/token-managers/container-token-manager.ts
auth/token-managers/cp4d-token-manager.ts
auth/token-managers/iam-request-based-token-manager.ts
auth/token-managers/iam-token-manager.ts
auth/token-managers/token-manager.ts
auth/token-managers/vpc-instance-token-manager.ts
package-lock.json

This commit refreshes the project's dependencies to address a high-sev vulnerability reported in the http-cache-semantics package.
Also included in this commit are minor changes to several .ts files in order to address eslint errors reported by the "import/no-cycle" rule.  These errors started showing up because the eslint-plugin-import package was also upgraded from 2.26.0 to 2.27.5 (the latest) as a result of refreshing the dependencies.

fix: refresh dependencies and address import cycles

---

lib/cookie-support.ts

This commit adds a couple of checks to avoid
problems while handling cookies found in error responses.

fix: harden checks for cookies in error responses

---

package-lock.json

Bumps the version of @babel/traverse (a transitive dependency) to avoid CVE-2023-45133.
This change was made simply by running `npm audit fix`.

fix: bump @babel/traverse to avoid CVE-2023-45133

---

package-lock.json
package.json

build(deps): bump axios from 1.4.0 to 1.6.0
Fixes #254

build(deps): bump axios from 1.4.0 to 1.6.0

---

.secrets.baseline
Authentication.md
auth/authenticators/authenticator.ts
auth/authenticators/index.ts
auth/authenticators/mcsp-authenticator.ts
auth/token-managers/index.ts
auth/token-managers/mcsp-token-manager.ts
auth/utils/get-authenticator-from-environment.ts
etc/ibm-cloud-sdk-core.api.md
test/integration/mcsp-authenticator.test.js
test/unit/get-authenticator-from-environment.test.js
test/unit/mcsp-authenticator.test.js
test/unit/mcsp-token-manager.test.js

This commit introduces the new McspAuthenticator that can be used to exchange an apikey for an MCSP access token using the Multi-Cloud Saas Platform authentication token server's 'POST /siusermgr/api/1.0/apikeys/token' operation.

feat(McspAuthenticator): add new authenticator for Multi-Cloud Saas Platform

---

.secrets.baseline
package-lock.json
package.json

fix(deps): bump axios to 1.6.3 to avoid ReDOS vulnerability

---

.secrets.baseline
package-lock.json
package.json

Fixes some newly discovered vulnerabilities. From the release notes:
> security: fixed formToJSON prototype pollution vulnerability; (https://github.com/axios/axios/issues/6167) ([3c0c11c](https://github.com/axios/axios/commit/3c0c11cade045c4412c242b5727308cff9897a0e))
security: fixed security vulnerability in follow-redirects (https://github.com/axios/axios/issues/6163) ([75af1cd](https://github.com/axios/axios/commit/75af1cdff5b3a6ca3766d3d3afbc3115bb0811b8))
Closes https://github.com/IBM/node-sdk-core/issues/264

fix(deps): bump axios to 1.6.4

---

auth/token-managers/token-manager.ts
test/unit/jwt-token-manager.test.js

This commit introduces a Promise rejection handler to the `getToken` method where it was previously lacking. The refresh token kick-off did not catch any exceptions, resulting in the program crashing when a refresh error occurred. Now, the error will be caught and logged but the logic will continue as-is and the request will be retried later.
Note: I also discovered that one of our tests wasn't actually doing what it said it was doing 🙂 So I updated it to match its intentions and added a new test to verify the behavior that should have been captured by it.

fix(token-manager): handle request errors when refreshing tokens

---

.secrets.baseline
auth/token-managers/iam-request-based-token-manager.ts
auth/token-managers/jwt-token-manager.ts
auth/token-managers/token-manager.ts
auth/token-managers/vpc-instance-token-manager.ts
etc/ibm-cloud-sdk-core.api.md
package-lock.json
test/unit/iam-token-manager.test.js
test/unit/vpc-instance-token-manager.test.js

This commit changes the IAM, Container and VPC Instance authenticators slightly so that an IAM access token will be viewed as "expired" when the current time is within 10 seconds of the official expiration time. IOW, we'll expire the access token 10 secs earlier than the IAM server-computed expiration time.
We're doing this to avoid a scenario where
an IBM Cloud service receives a request along
with an "almost expired" access token and then uses that token to perform downstream requests in a
somewhat longer-running transaction and then the
access token expires while that transaction is
still active.

fix: adjust IAM token expiration time

---

.secrets.baseline
auth/token-managers/container-token-manager.ts
auth/token-managers/cp4d-token-manager.ts
auth/token-managers/iam-request-based-token-manager.ts
auth/token-managers/iam-token-manager.ts
auth/token-managers/mcsp-token-manager.ts
auth/token-managers/token-manager.ts
auth/token-managers/vpc-instance-token-manager.ts
etc/ibm-cloud-sdk-core.api.md
lib/base-service.ts
lib/build-user-agent.ts
test/unit/base-service.test.js
test/unit/container-token-manager.test.js
test/unit/cp4d-token-manager.test.js
test/unit/iam-request-based-token-manager.test.js
test/unit/iam-token-manager.test.js
test/unit/mcsp-token-manager.test.js
test/unit/utils.js
test/unit/vpc-instance-token-manager.test.js

This commit updates our various request-based authenticators so that the User-Agent header is included with each outbound token request. The value of the User-Agent header will be of the form `ibm-node-sdk-core/<authenticator-type>-<core-version> <os-info>`.
Edit: I also updated `BaseService.createRequest()` so that it will add a default User-Agent header to the outbound request if one was not passed in with the request options.

feat: send user-agent header with auth token requests

---

lib/sdk-test-helpers.ts
package-lock.json
package.json
test/unit/serializer-deserializer.test.js

We previously exposed the `expect` package as a production-level dependency, because this package includes unit test utility functions for SDK libraries that depend on this package. However, `expect` is meant to be a development dependency and introduces some sizebloat and vulnerability attack surface to this package.
Fortunately, the `expect` package is intended to be used from `jest` and is not required to be installed on its own unless specifically needed. Since all SDK libraries depending on this package also use `jest`, it is redundant to include the dependency in this package. The test utilities provided will never be run in production and the SDKs will be able to run their tests using the already-installed `jest` package. For this reason, `expect` is removed in this commit. …

fix(deps): remove `expect` as redundant development dependency

---

package-lock.json
package.json

fix(deps): update axios to resolve vulnerability

---

.secrets.baseline
Authentication.md
README.md
auth/authenticators/authenticator.ts
auth/authenticators/container-authenticator.ts
auth/authenticators/iam-assume-authenticator.ts
auth/authenticators/iam-authenticator.ts
auth/authenticators/iam-request-based-authenticator-immutable.ts
auth/authenticators/iam-request-based-authenticator.ts
auth/authenticators/index.ts
auth/authenticators/token-request-based-authenticator-immutable.ts
auth/authenticators/token-request-based-authenticator.ts
auth/token-managers/container-token-manager.ts
auth/token-managers/iam-assume-token-manager.ts
auth/token-managers/iam-request-based-token-manager.ts
auth/token-managers/iam-token-manager.ts
auth/token-managers/index.ts
auth/utils/get-authenticator-from-environment.ts
auth/utils/helpers.ts
etc/ibm-cloud-sdk-core.api.md
package.json
test/integration/iam-assume-authenticator.test.js
test/unit/container-token-manager.test.js
test/unit/iam-assume-authenticator.test.js
test/unit/iam-assume-token-manager.test.js
test/unit/iam-request-based-authenticator.test.js
test/unit/iam-request-based-token-manager.test.js

This commit introduces the new IamAssumeAuthenticator which will fetch an IAM access token using the IAM getToken operation's "assume" grant type. The resulting access token allows the application to assume the identity of a trusted profile, similar to the "sudo" feature of Linux.

feat(IamAssumeAuthenticator): add new authentication type for iam assume

---

.releaserc
package-lock.json
package.json

Fixes the format of the .releaserc file to comply with the semrel docs.

fix(build): fix .releaserc format

---

Authentication.md
auth/token-managers/container-token-manager.ts

This pull request extends the existing ContainerAuthenticator to be aware of the hard-coded compute resource token path used by Code Engine. This allows a seamless usage of that authenticator and a move of workload between IKS/ROKS/Code Engine without changing a single line of code.
Documentation is adjusted to mention Code Engine in the context of the ContainerAuthenticator.

feat(ContainerAuthenticator): enhance ContainerAuthenticator to support Code Engine workload

---

package-lock.json
package.json

fix(deps): upgrade axios to 1.8.2 https://github.com/advisories/GHSA-jr5f-v2jv-69x6
With this change, this repo should have safe version for axios.
```sh
$ npm ls axios
ibm-cloud-sdk-core@5.1.2 /Users/akira/dev/node-sdk-core
├── axios@1.8.2
└─┬ retry-axios@2.6.0
└── axios@1.8.2 deduped
```

fix(deps): upgrade axios to 1.8.2

---

.github/workflows/build.yaml
.secrets.baseline
Authentication.md
auth/authenticators/authenticator.ts
auth/authenticators/index.ts
auth/authenticators/mcsp-authenticator.ts
auth/authenticators/mcspv2-authenticator.ts
auth/token-managers/index.ts
auth/token-managers/jwt-token-manager.ts
auth/token-managers/mcspv2-token-manager.ts
auth/token-managers/token-manager.ts
auth/utils/get-authenticator-from-environment.ts
etc/ibm-cloud-sdk-core.api.md
lib/request-wrapper.ts
package-lock.json
test/integration/mcspv2-authenticator.test.js
test/unit/get-authenticator-from-environment.test.js
test/unit/mcsp-token-manager.test.js
test/unit/mcspv2-authenticator.test.js
test/unit/mcspv2-token-manager.test.js

This commit adds the McspV2Authenticator implementation. This authenticator will invoke the MCSP V2 POST
/api/2.0/{scopeCollectionType}/{scopeId}/apikeys/token operation to obtain an access token for an apikey.

feat(auth): add support for MCSP V2 authentication

---

package-lock.json
package.json

Bumps axios to 1.11.0 to avoid vulnerabilities.

fix(deps): bump axios to 1.11.0 to avoid CVEs

---

package-lock.json
package.json

Bumps axios to 1.12.2 to avoid vulnerabilities.

fix(deps): bump axios to 1.12.2 to avoid CVEs
